config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:new, :create, :index]
  
  get 'login'   => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  post 'login'  => 'sessions#create'
  get 'new_post' => 'posts#new'
  root 'posts#index'
  
  

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    
end

app/models/user.rb
class User < ActiveRecord::Base
    
    before_save { self.email = email.downcase }
    before_create :add_remember_token
    
    validates :email, presence: true
    validates :username, presence: true
    
    has_secure_password
    has_many :posts
    
    
    
    def User.generate_remember_token
        SecureRandom.urlsafe_base64
    end
    
    def User.digest(token)
        Digest::SHA1.hexdigest(token.to_s)
    end
        
    
    
    private
        
        def add_remember_token
           
           self.remember_token = User.digest(User.generate_remember_token)
           
        end
           
            
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  
  
  
    
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_filter :logged_in_user?, only: [:new, :create]
    
    def new
        @post = Post.new
    end
    
    def create
        
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        @post.save
        redirect_to root_path
        
    end
    
    def index
        @posts = Post.all
    end
    
    
    private
        
        def post_params
            params.require(:post).permit(:body)
        end
        
        def logged_in_user?
            unless logged_in?
                redirect_to login_path
                flash[:danger] = "You must log in to post"
            end
        end
        
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Thanks for signing in"
      sign_in(user)
      redirect_to root_path
    else
      flash[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end
    
  def destroy
    sign_out
    flash.now[:success] = "You've logged out"
    redirect_to root_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def sign_in(user)
    remember_token = User.generate_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
    
    end
  
  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end 
  
  def current_user=(user)
    @current_user = user
  end
  
  def sign_out
  # current_user.update_attribute(:remember_token,
   #                             User.digest(User.generate_remember_token))
  cookies.delete(:remember_token)
  self.current_user = nil
  @current_user = nil
  end
    
    
    
    def logged_in?
    !current_user.nil?
    end
    
    
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Members Only", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "New Post", new_post_path %></li>
           <% if logged_in? %>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <%else%>
              <li><%= link_to "Log in", login_path %></li>
            <%end%>
          </ul>
        </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
<div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%=message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>

    <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/posts/index.html.erb
 <div class="row">
    <div class="col-md-6 col-md-offset-1">
    <h1> Posts </h1>

    <% @posts.each do |post| %>
        <% if logged_in? %>
            <h4>Written by: <%= post.user.username %></h4>
        <%else%>
            <h4> Written by: <%=link_to "Log in to see", login_path %></h4>
        <%end%>
      
        <%= post.body %>  </br></br>
    <% end %>
</br></br>
</div>
</div>

app/views/posts/new.html.erb
<h1>New Post </h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for @post do |f| %>
        
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control" %> <br/>
        
        <%= f.submit "Submit Post", class: "btn btn-primary" %>
        
        <%end%>
    </div>
</div>